collections:
    training:
      output: true
    research:
      output: true
   

# Site settings
title: QuadraLogics
email: info@quadralogics.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

#Heading 
Head1: + + DevOps
Head2: A Premier DevXOps Training & Consulting Firm
Head3: ↑Speed ↑Quality ↓Cost ↑Happiness

#Call to action
USPH: Most trusted DevOps training producers!
USP: Quadralogics is a boutique training firm that specializes in DevOps training and consulting. Since our inception in 2014, QuadraLogics has facilitated more than 70+ corporate and public workshops enabling more than 2000+ practitioners. We are trusted partners with global brands like Pluralsight, Udacity, KnowledgeHut, etc and enable them in designing/delivering technical content and training. Quadralogics today is one of the most trusted training/content producers and a premium player in the B2B DevOps market.

#services
ServicesHeading: At Your Service

Services1H: Training Services
Services1: Quadralogics today is one of the most trusted training providers and a premium player in the B2B DevOps market. Since our inception in 2014, QuadraLogics has facilitated more than 70+ corporate workshops enabling more than 2000+ practitioners in India and Abroad. Do reach out to your DevOps training needs.

Services2H: Content Development
Services2: As a DevOps training producer and video content provider, we have been regularly enabling our partners with up to date & state of the art training content. Few of our global partners include Pluralsight, Udacity, Coursera, etc. We regularly partner with Corporates and Universities to handcraft a highly tailored value-driven Curriculum.

Services3H: Consulting, Advisory & Research
Services3: Successful DevOps implementations rely on an integrated set of solutions or a "toolchain" to improve automation and increase your team's technical agility. Our dedicated team of qualified and experienced DevOps consultants will enable you to deliver high-quality products, faster. 

Services4H: Public DevOps Workshops
Services4: We regularly facilitate Hands-on Public Workshop. Do Scroll down to see our current ongoing public workshops. Among the spectrum of all our workshops, the “DevOps Master Workshop” series is our flagship public training and is one of the most rated trainings in the market. This 12-week hands-on workshop includes 72 hours of training & covers 11 tools across 200+ real-life scenarios.


#Clinets
clinetsH : Our Clients

#Ribbon 
RHead1: Current Public Workshops
RHead2: DevOps Master Architect Workshop!
RHead3: 72 hours | 11 tools | 200+ hands-on Senarios
RCTA:  Click to know more

ph_number: +91-6362315334
github_username: linkedin/company/quadralogics

footer: ©  2020  www.quadralogics.com

# Build settings
markdown: kramdown
